name: karabiner_observer

targets:
  karabiner_observer:
    settings:
      CODE_SIGN_ENTITLEMENTS: ''
      CODE_SIGN_IDENTITY: '-'
      CODE_SIGN_STYLE: Manual
      SYSTEM_HEADER_SEARCH_PATHS:
        - ../../vendor/cget/include
        - ../../vendor/Karabiner-DriverKit-VirtualHIDDevice/include
      HEADER_SEARCH_PATHS:
        - include
        - ../../share
    type: tool
    platform: macOS
    deploymentTarget: 10.15
    sources:
      - path: src
        compilerFlags:
          - -Wall
          - -Werror
          - '-std=gnu++2a'
    dependencies:
      - framework: CoreServices.framework
      - framework: IOKit.framework
