name: Karabiner-Elements
packages:
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: 1.26.0

targets:
  Karabiner-Elements:
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: org.pqrs.Karabiner-Elements.Updater
      CODE_SIGN_ENTITLEMENTS: ''
      CODE_SIGN_IDENTITY: '-'
      CODE_SIGN_STYLE: Manual
    type: application
    platform: macOS
    deploymentTarget: 10.15
    sources:
      - path: src
        compilerFlags:
          - -Wall
          - -Werror
      - path: Resources
        excludes:
          - .gitignore
          - '*.plist.in'
      - path: ../share/Resources/app.icns
    dependencies:
      - package: Sparkle
