name: Karabiner-Elements

targets:
  Karabiner-Elements:
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: org.pqrs.Karabiner-Elements.Updater
      CODE_SIGN_ENTITLEMENTS: ''
      CODE_SIGN_IDENTITY: '-'
      CODE_SIGN_STYLE: Manual
      SYSTEM_HEADER_SEARCH_PATHS:
        - ../../vendor/cget/include
      HEADER_SEARCH_PATHS:
        - ../../lib/libkrbn/include
    type: application
    platform: macOS
    deploymentTarget: 10.15
    sources:
      - path: src
        compilerFlags:
          - -Wall
          - -Werror
      - path: Resources
        excludes:
          - .gitignore
          - '*.plist.in'
      - path: ../share/Resources/app.icns
    dependencies:
      - framework: ../../vendor/Sparkle/build/Build/Products/Release/Sparkle.framework
